version: '3'
services:
  app:
    container_name: boardgame-app
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    environment:
      PORT: '8080'
    env_file:
      - src/.env
    depends_on:
      - database

  database:
    image: postgres
    restart: always
    container_name: database
    ports:
      - '5432:5432'
    env_file:
      - src/.env
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
