// Code generated by MockGen. DO NOT EDIT.
// Source: setup_test.go
//
// Generated by this command:
//
//	mockgen -package tests -destination mock_database_test.go -source setup_test.go
//

// Package tests is a generated GoMock package.
package tests

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDatabase is a mock of Database interface.
type MockDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseMockRecorder
	isgomock struct{}
}

// MockDatabaseMockRecorder is the mock recorder for MockDatabase.
type MockDatabaseMockRecorder struct {
	mock *MockDatabase
}

// NewMockDatabase creates a new mock instance.
func NewMockDatabase(ctrl *gomock.Controller) *MockDatabase {
	mock := &MockDatabase{ctrl: ctrl}
	mock.recorder = &MockDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabase) EXPECT() *MockDatabaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDatabase) Create(value any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDatabaseMockRecorder) Create(value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDatabase)(nil).Create), value)
}

// Delete mocks base method.
func (m *MockDatabase) Delete(value any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDatabaseMockRecorder) Delete(value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDatabase)(nil).Delete), value)
}

// Read mocks base method.
func (m *MockDatabase) Read(value any, sort, search, identifier string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", value, sort, search, identifier)
	ret0, _ := ret[0].(error)
	return ret0
}

// Read indicates an expected call of Read.
func (mr *MockDatabaseMockRecorder) Read(value, sort, search, identifier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockDatabase)(nil).Read), value, sort, search, identifier)
}

// ReplaceAssociatons mocks base method.
func (m *MockDatabase) ReplaceAssociatons(model any, association string, values any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceAssociatons", model, association, values)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceAssociatons indicates an expected call of ReplaceAssociatons.
func (mr *MockDatabaseMockRecorder) ReplaceAssociatons(model, association, values any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceAssociatons", reflect.TypeOf((*MockDatabase)(nil).ReplaceAssociatons), model, association, values)
}

// Update mocks base method.
func (m *MockDatabase) Update(value any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDatabaseMockRecorder) Update(value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDatabase)(nil).Update), value)
}
